# Generated by Django 3.0.5 on 2020-05-15 15:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20200515_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 18, 0, 15, 991719)),
        ),
        migrations.AlterField(
            model_name='message',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages', to='forum.Theme'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 18, 0, 15, 990722)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 18, 0, 15, 990722)),
        ),
    ]
