# Generated by Django 3.0.5 on 2020-05-15 15:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20200515_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 18, 14, 26, 845634)),
        ),
        migrations.AlterField(
            model_name='theme',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 18, 14, 26, 845634)),
        ),
        migrations.AlterField(
            model_name='theme',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='themes', to='forum.Topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 18, 14, 26, 844644)),
        ),
    ]
