# Generated by Django 3.0.5 on 2020-05-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20200515_2201'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['create_date'], name='forum_topic_create__c48cf0_idx'),
        ),
    ]
