# Generated by Django 3.0.5 on 2020-05-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20200525_1510'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='topic',
            name='forum_topic_create__c48cf0_idx',
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['-create_date'], name='forum_topic_create__0dbe7d_idx'),
        ),
    ]
