# Generated by Django 3.0.5 on 2020-05-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200501_1612'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['pub_date'], name='news_post_pub_dat_14ff8b_idx'),
        ),
    ]
