# Generated by Django 3.0.5 on 2020-05-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200525_1510'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='news_post_pub_dat_14ff8b_idx',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-pub_date'], name='news_post_pub_dat_1b3cde_idx'),
        ),
    ]
