# Generated by Django 3.0.5 on 2020-05-15 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20200515_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='description',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 21, 40, 4, 169115)),
        ),
        migrations.AlterField(
            model_name='theme',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 21, 40, 4, 169115)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 21, 40, 4, 168118)),
        ),
    ]
